### ISSUE TITLE
ErgoDoxを使って一週間くらいになるのでしょうか？

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw-posts#46]
記事用画像うｐ

![keyboard-layout](https://cloud.githubusercontent.com/assets/1443118/18747027/e0112034-8105-11e6-9d0a-700ee80da858.png)
![keyboard-layout 3](https://cloud.githubusercontent.com/assets/1443118/18747028/e1049674-8105-11e6-883b-ddba94a50579.png)
![typing1](https://cloud.githubusercontent.com/assets/1443118/18747292/7c369fec-8107-11e6-98fe-c16f4e478369.png)
![typing2](https://cloud.githubusercontent.com/assets/1443118/18747294/7d5ccf7c-8107-11e6-8f7c-d235dfd5eacf.png)
![img_5301](https://cloud.githubusercontent.com/assets/1443118/18747578/11d6b39c-8109-11e6-9936-5f85f2acce31.JPG)

**Comment by trkw** [comment]
とうとう安定してきたかな？

**Comment by trkw** [comment]
Backspaceの位置がすげぇ

**Comment by miyaoka** [comment]
思ったより長くなったけど、まだ書き足りない。次はエルゴノミクスについて書こう
